// Generated by gencpp from file roswell_navigation/ReturnJointStates.msg
// DO NOT EDIT!


#ifndef ROSWELL_NAVIGATION_MESSAGE_RETURNJOINTSTATES_H
#define ROSWELL_NAVIGATION_MESSAGE_RETURNJOINTSTATES_H

#include <ros/service_traits.h>


/*
#include <roswell_navigation/ReturnJointStatesRequest.h>
#include <roswell_navigation/ReturnJointStatesResponse.h>
*/
#include "ReturnJointStatesRequest.h"
#include "ReturnJointStatesResponse.h"


namespace roswell_navigation
{

struct ReturnJointStates
{

typedef ReturnJointStatesRequest Request;
typedef ReturnJointStatesResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ReturnJointStates
} // namespace roswell_navigation


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::roswell_navigation::ReturnJointStates > {
  static const char* value()
  {
    return "ce9bd2b56c904b190a782a08482fb4e9";
  }

  static const char* value(const ::roswell_navigation::ReturnJointStates&) { return value(); }
};

template<>
struct DataType< ::roswell_navigation::ReturnJointStates > {
  static const char* value()
  {
    return "roswell_navigation/ReturnJointStates";
  }

  static const char* value(const ::roswell_navigation::ReturnJointStates&) { return value(); }
};


// service_traits::MD5Sum< ::roswell_navigation::ReturnJointStatesRequest> should match 
// service_traits::MD5Sum< ::roswell_navigation::ReturnJointStates > 
template<>
struct MD5Sum< ::roswell_navigation::ReturnJointStatesRequest>
{
  static const char* value()
  {
    return MD5Sum< ::roswell_navigation::ReturnJointStates >::value();
  }
  static const char* value(const ::roswell_navigation::ReturnJointStatesRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::roswell_navigation::ReturnJointStatesRequest> should match 
// service_traits::DataType< ::roswell_navigation::ReturnJointStates > 
template<>
struct DataType< ::roswell_navigation::ReturnJointStatesRequest>
{
  static const char* value()
  {
    return DataType< ::roswell_navigation::ReturnJointStates >::value();
  }
  static const char* value(const ::roswell_navigation::ReturnJointStatesRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::roswell_navigation::ReturnJointStatesResponse> should match 
// service_traits::MD5Sum< ::roswell_navigation::ReturnJointStates > 
template<>
struct MD5Sum< ::roswell_navigation::ReturnJointStatesResponse>
{
  static const char* value()
  {
    return MD5Sum< ::roswell_navigation::ReturnJointStates >::value();
  }
  static const char* value(const ::roswell_navigation::ReturnJointStatesResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::roswell_navigation::ReturnJointStatesResponse> should match 
// service_traits::DataType< ::roswell_navigation::ReturnJointStates > 
template<>
struct DataType< ::roswell_navigation::ReturnJointStatesResponse>
{
  static const char* value()
  {
    return DataType< ::roswell_navigation::ReturnJointStates >::value();
  }
  static const char* value(const ::roswell_navigation::ReturnJointStatesResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROSWELL_NAVIGATION_MESSAGE_RETURNJOINTSTATES_H
